version: 2.1
jobs:
  build:
    machine:  # docker executor ではなく machine executor を使用する; https://circleci.com/ja/blog/building-docker-images-for-multiple-os-architectures/ - CI パイプラインを設定する
      image: ubuntu-2004:202111-01  # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - run:  # pull-req only
          name: Build Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              make build
            fi
      - run:  # pull-req only
          name: Test Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              make test
            fi
      - run:  # main branch only
          name: Log in to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
            fi
      - run:  # main branch only
          name: Install buildx
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64"
              curl --output docker-buildx \
                --silent --show-error --location --fail --retry 3 \
                "$BUILDX_BINARY_URL"

              mkdir -p ~/.docker/cli-plugins

              mv docker-buildx ~/.docker/cli-plugins/
              chmod a+x ~/.docker/cli-plugins/docker-buildx

              docker buildx install
              # Run binfmt
              docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            fi
      - run:  # main branch only
          name: Cross-build and push
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              BUILDX_PLATFORMS="$BUILDX_PLATFORMS" make cross-build-and-push
            fi
