version: 2.1
jobs:
  build:
    machine:  # docker executor ではなく machine executor を使用する; https://circleci.com/ja/blog/building-docker-images-for-multiple-os-architectures/ - CI パイプラインを設定する
      image: ubuntu-2004:202111-01  # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      # - run:
      #     name: Build from dockerfile
      #     command: |
      #       make build
      # - run:
      #     name: Test Docker image
      #     command: |
      #       make test
      # - run:
      #     name: Log in to docker hub
      #     command: |
      #       docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run:
      #     name: Push to docker hub
      #     command: |
      #       make push
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run:
          name: Tag golden
          command: |
            BUILDX_PLATFORMS="$BUILDX_PLATFORMS" make cross-build
      - run:
          name: show docker images
          command: |
            docker images
