version: 2.1
executors:
  builder:
    machine:
      image: ubuntu-2004:202111-02  # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

commands:  # https://circleci.com/docs/ja/2.0/reusing-config/
  build-image:
    parameters:
      arch:
        type: string
    steps:
      - checkout
      - run:
          name: Build a docker image
          command: |
            make build-ci
      - run:
          name: Install test tools
          command: |
            sudo apt update -qq
            sudo apt install -y -qq moreutils
            mkdir ~/opt
            tar xf prefetched/*/nodejs.tar.gz -C ~/opt --strip-components 1
            PATH=${PATH}:~/opt/bin npm install --global --silent --no-progress tap-xunit
            echo "export PATH=${PATH}:~/opt/bin" >> ${BASH_ENV}
      - run:
          name: Test a docker image
          command: |
            mkdir ~/reports
            make test-ci | pee cat "tap-xunit > ~/reports/result.xml"
      - store_test_results:
          path: ~/reports

jobs:
  build-x64:
    executor: builder
    environment:
      DOCKER_BUILDKIT: '1'
    resource_class: large  # 4vCPU, 8GB RAM; https://circleci.com/docs/ja/2.0/configuration-reference/#resourceclass
    steps:
      - build-image:
          arch: amd64

workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - build-x64
