version: 2.1
executors:
  ubuntu-2004:
    machine:  # docker executor ではなく machine executor を使用する; https://circleci.com/ja/blog/building-docker-images-for-multiple-os-architectures/ - CI パイプラインを設定する
      image: ubuntu-2004:202111-01  # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

jobs:
  build-test-push:
    executor: ubuntu-2004
    environment:
      DOCKER_BUILDKIT: "1"
      NODE_VERSION: v16.13.1
    steps:
      - checkout
      - run:
          name: Build the Docker image
          command: |
            make build-ci
      - run:
          name: Install test tools
          # npm を apt でインストールすると遅いため tar をダウンロードして展開
          command: |
            apt update
            apt install -y moreutils
            curl -L https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz | tar xf -
            node-*-linux-x64/bin/npm install --global --silent --no-progress tap-xunit
      - run:
          name: Test the Docker image
          command: |
            mkdir ~/reports
            make test-ci | pee cat "node-*-linux-x64/bin/tap-xunit > ~/reports/result.xml"
      - store_test_results:  # 以前のテストステップが失敗しても実行される
          path: ~/reports
      - run: |  # main ブランチがターゲットでない場合はステップ内からジョブを停止する
          if [ "$CIRCLE_BRANCH" != "main" ]; then
            circleci-agent step halt
          fi
      - run:
          name: Login to Docker Hub
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Push the Docker image
          command: |
            make push

  cross-build-push:  # buildx でのクロスビルド時に load ができず push するため、ここではテストを実行しない
    # filters:  # main ブランチのみ
    #   branches:
    #     only:
    #       - main
    executor: ubuntu-2004
    environment:
      DOCKER_BUILDKIT: "1"
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
      # BUILDX_BINARY_URL: https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
      # - run:
      #     name: Install Buildx
      #     command: |
      #       curl -sfSL --retry 3 "$BUILDX_BINARY_URL" -o docker-buildx 
      #       mkdir -p ~/.docker/cli-plugins
      #       mv docker-buildx ~/.docker/cli-plugins/
      #       chmod a+x ~/.docker/cli-plugins/docker-buildx
      #       docker buildx install
      #       docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run:
          name: Cross-build and push
          command: |
            make cross-build-and-push

workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - build-test-push
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "30 * * * *" # 毎時 30 分
          filters:
            branches:
              only:
                - main
    jobs:
      - cross-build-push
